baseURL = 'https://little-red-lamp.neocities.org/'
locale = 'en-us'
title = 'Little Red Lamps'

theme = 'risotto'

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10